### ISSUE TITLE
max-w-... look into width instead on maxWidth in theme in safari

### ISSUE THREAD

**Issue by efflam** [tw-in-js/twind#185] opened 2021-05-31 10:09 UTC
It looks like Safari is looking for a value in `width` instead of `maxWidth` in the theme for the `max-w-...` directive.
For example, with `max-w-xl`, I have this warning and the max width style is not set :
`[UNKNOWN_THEME_VALUE] {"key":"width.xl"}
unknown — twind.js:929`

If I add 
```
width: {
  xl: "36rem"
}
```
to the theme, it works.

**Comment by sastan** [comment] 2021-06-02 06:36
I tried to reproduce this and couldn't find an issue (see 408870c). Could you please provide a codesandbox?

**Comment by gojutin** [comment] 2021-06-02 13:28
I was also unable to reproduce the issue in Safari:

https://codesandbox.io/s/twind-issue-185-se41v

**Comment by Secretmapper** [comment] 2021-08-01 04:18
The bug seems to be reproducible by using custom spacing variables:

https://codesandbox.io/s/twind-issue-185-forked-55hf6?file=/src/index.ts

**Comment by undlmn** [comment] 2021-11-25 14:36
I have the same error (safari only)

problem is here:
https://github.com/tw-in-js/twind/blob/e04ae1f6a069fa49e8694a2ee36f4fe6207f38a4/src/twind/plugins.ts#L265
This is because Safari first call the theme function, and only then calculates the key for the object.
first called theme('width' <-!! , tail(params)) and then created object {'minWidth': <result>}

as a temporary solution:
`
setup({
  plugins: {
    min: minMax,
    max: minMax,
  }
});

function minMax([k, ...rest], { theme }, id) {
  const key = { w: `${id}Width`, h: `${id}Height` }[k];
  if (key) return { [key]: theme(key, rest) };
}
`

**Comment by sastan** [comment] 2022-01-25 18:54
This is fixed in v1. Please give it a try. Here are some links to get you started:

- [The v1 branch](https://github.com/tw-in-js/twind/tree/next)
- [Reference](https://github.com/tw-in-js/twind/blob/next/documentation/40-reference/README.md) until the website is ready
- [Examples](https://github.com/tw-in-js/twind/tree/next/examples) — the [CDN example](https://github.com/tw-in-js/twind/tree/next/examples/twind-cdn) could be a good start

Closing this for now. Feel free to re-open.

**Closed by sastan** 2022-01-25 18:54 UTC
Labels: ❓ Question
