### ISSUE TITLE
Twind with Preact WMR

### ISSUE THREAD

**Issue by nmasella** [tw-in-js/twind#33] opened 2020-12-29 19:08 UTC
Hi,this is an amazing tool, thank you for you work. I'll try to use twind inside the new Preact WMR ( https://github.com/preactjs/wmr ) but with the only npm install twind and tailwindcss and the following use:

```
import { useState } from 'preact/hooks';
import { tw } from 'twind'

export default function Home() { 
 return ( 
<> 
<p>Hi!</p> 
<h1 className={tw`font-bold text(center 5xl white sm:gray-800 md:pink-700)`}>This is Twind!</h1> 
</> );
}
```

doesn't work, i have a white page and no error as output of npm run start. Is it possible to use with Preact WMR?
Thank you.

**Comment by rschristian** [comment] 2020-12-29 19:14
Is there anything in the browser console? WMR at the moment I think swallows all thrown warnings/errors

**Comment by sastan** [comment] 2020-12-29 19:50
In the browser console i see the following error:

```
Uncaught SyntaxError: The requested module '/@npm/tiny-css-prefixer' does not provide an export named 'default'
```

It seems like WMR is doing two curious things:

1. it is using our CJS bundle or at least it sems like it: `var twind = createCommonjsModule(function (module, exports) {`
2. it tries to use the default export from tiny-css-prefixer which does not have a default export: `import tinyCssPrefixer from '/@npm/tiny-css-prefixer'`

I don't know how to investigate any further... Maybe you could create an issue in the wmr repo.  If you need any help explaining, reproducing or investigating feel free to reach out to me.

**Comment by sastan** [comment] 2020-12-29 19:52
One other thing: You should not need to install tailwindcss. Twind works without tailwindcss or postcss.

**Comment by lukejacksonn** [comment] 2020-12-29 21:57
I know that @smeijer has been trying to use Twind with WMR, he might have some insight. More generally @JoviDeCroock might know whats up with WMR trying to use the CJS version of `tiny-css-prefixer`.

Given that it is our only dependency and is tiny.. I wonder if it is just worth vendoring (@kitten might be able to evaluate this risk better than us but it looks like it doesn't get updated too often) 🤔

**Comment by kitten** [comment] 2020-12-29 21:58
It probably either insists on `.mjs` or an exports entry, so that should be an easy fix

**Comment by sastan** [comment] 2020-12-29 22:21
I think there is some deeper problem. it seems like wmr is using **our** CJS bundle when instead it should use the es module.

The problem with tiny-css-prefixer is that wmr uses the default export altough it has only named exports.

Maybe both issues are related...

**Comment by JoviDeCroock** [comment] 2020-12-29 22:23
I think you'll have to add the `module` field to the `package.json` your current `main` export indicates that you are exporting a CJS export. This is the current "standard"

**Comment by lukejacksonn** [comment] 2020-12-29 22:51
This sounds like the solution.. I forgot about `module` field! We should try that out @sastan. Thank you both @JoviDeCroock and @kitten for such swift responses 🙇

**Comment by sastan** [comment] 2020-12-29 23:04
We have a module field in the package.json. The package.json in the repo is not the that is published. Here is an example:

```json
{
  "name": "twind",
  "version": "0.10.1",
  "main": "./twind.cjs",
  "exports": {
    ".": {
      "node": "./twind.cjs",
      "script": "./twind.umd.js",
      "types": "./twind.d.ts",
      "default": "./twind.js"
    },
    "./colors": {
      "node": "./colors/colors.cjs",
      "script": "./colors/colors.umd.js",
      "types": "./colors/colors.d.ts",
      "default": "./colors/colors.js"
    },
    "./css": {
      "node": "./css/css.cjs",
      "script": "./css/css.umd.js",
      "types": "./css/css.d.ts",
      "default": "./css/css.js"
    },
    "./observe": {
      "node": "./observe/observe.cjs",
      "script": "./observe/observe.umd.js",
      "types": "./observe/observe.d.ts",
      "default": "./observe/observe.js"
    },
    "./shim": {
      "node": "./shim/shim.cjs",
      "script": "./shim/shim.umd.js",
      "types": "./shim/shim.d.ts",
      "default": "./shim/shim.js"
    },
    "./server": {
      "types": "./server/server.d.ts",
      "default": "./server/server.cjs"
    },
    "./sheets": {
      "node": "./sheets/sheets.cjs",
      "script": "./sheets/sheets.umd.js",
      "types": "./sheets/sheets.d.ts",
      "default": "./sheets/sheets.js"
    },
    "./package.json": "./package.json"
  },
  "sideEffects": [
    "./dist/shim/shim.js"
  ],
  "module": "./twind.js",
  "unpkg": "./twind.umd.js",
  "types": "./twind.d.ts"
}
```

**Comment by lukejacksonn** [comment] 2020-12-30 00:46
Interesting.. I will take a proper look at this tomorrow!

**Comment by rschristian** [comment] 2020-12-30 00:55
It's something with the exports. Wiping them out from the installed module (and then deleting WMR's `.cache/` inside the module) resolved the issue.

**Comment by lukejacksonn** [comment] 2020-12-30 01:14
Thanks for looking into this @rschristian! I'm still not sure wether this is twind, wmr or tiny-css-prefixer 🤔

**Comment by rschristian** [comment] 2020-12-30 01:25
I'm thinking `"node"` is the wrong key to be using as [it's going to match (and be used) with even NodeJS environment](https://nodejs.org/api/packages.html#packages_conditional_exports). Though WMR seems to get lost following this and tries to import a default from tiny-css. I don't believe it's tiny-css's fault.

I'm hardly an expert here though. Just fumbling my way through.

**Comment by developit** [comment] 2020-12-30 04:57
I believe we may have a pending change to export field precedence that has yet to be released. Not 100% sure, but if someone can try `wmr` from master that would confirm.

**Comment by rschristian** [comment] 2020-12-30 05:01
@developit No dice. I was trying that earlier just to see if it was something that has been addressed.

**Comment by sastan** [comment] 2020-12-30 07:01
Maybe we are  doing something wrong or could improve the exports definitions. Here are our intentions:

- node: a CJS bundle (target: node10.13) – as we have global state (`setup` changes `tw`) we want nodejs to use always the same bundle (see [Conditional exports](https://nodejs.org/api/packages.html#packages_conditional_exports) and [Dual package hazard](https://nodejs.org/api/packages.html#packages_dual_package_hazard))
- script: a UMD bundle (target: es2015) – to be used from a normal script tag without module system (see [exports field (webpack guideline)](https://gist.github.com/sokra/e032a0f17c1721c71cfced6f14516c62#reference-syntax))
- types: our typescript definitions – to be use from typescript that is interested in type declarations (see [exports field (webpack guideline)](https://gist.github.com/sokra/e032a0f17c1721c71cfced6f14516c62#reference-syntax))
- default: a ESM bundle (target: chrome79,firefox78,safari13.1,edge79) – to be used from cdn, bundlers and browsers, eg all conditions not met above (see [Conditional exports](https://nodejs.org/api/packages.html#packages_conditional_exports))

**Comment by JoviDeCroock** [comment] 2020-12-30 09:27
It should be fixed by adding import/module as a key to the export maps. The node one is exporting CJS so afaik require is a more appropriate key, default is a 'last resort'. https://github.com/preactjs/wmr/blob/master/src/plugins/npm-plugin/resolve.js#L80

**Comment by sastan** [comment] 2020-12-30 10:48
Thanks for the insight into how wmr is resolving modules. That helps a lot.

To summarize we need a single file that is consumed by node because of our shared state and a clear way to differentiate between node and browser bundles. The problem we have when used with wmr is that it selects `node` before `default` - which is the correct behaviour as `default` is the fallback.

I do not understand why `wmr` is using `node` when bundling for the browser? @JoviDeCroock Could you please elaborate on this. Thank you.

---

Which keys/conditions should be used for our two bundles in question (node and browser)?

Looking at the keys `['esmodules', 'import', 'module', 'require', 'browser', 'node', 'default']`:

- `esmodules`:  never seen this – What is this meant for? 
- `import`: If we add `import` that may get picked up by node and lead to duplicate state as we still need the `require` on as well. We can not use an esm wrapper as `import` will be picked up by bundlers for the browser.  For me that means `import` can not be used as it is too ambiguous.
- `module`: only used by bundlers - may work; but i'm a somehow unsure and may prefer `browser`
- `require`: see `import`
- `browser`: i would like to / prefer  this one for the browser ESM bundle
-  `node`: the node CJS bundle
- `default`: i really don't know where this should point now - may best guess is to the browser ESM bundle

What i would propose would be adding a `browser` field which points to the ESM bundle. Something like this:

```json
{
  "main": "./twind.cjs",
  "exports": {
    ".": {
      "browser": "./twind.js"
      "node": "./twind.cjs",
      "script": "./twind.umd.js",
      "types": "./twind.d.ts",
      "default": "./twind.js"
    }
  },
  "module": "./twind.js",
  "unpkg": "./twind.umd.js",
  "types": "./twind.d.ts"
}
```

**Comment by JoviDeCroock** [comment] 2020-12-30 10:50
`wmr` doesn't only render for the browser, it also aims to support things like creating an ssr-bundle which to support older versions of Node forces us to support CJS (exports.node). We also have a prerender mode which forces our hand at this as well.

**Comment by sastan** [comment] 2020-12-30 10:52
That makes sense. Taking that into account – `module` would be the way to go?

Something like that:

```js
{
  "main": "./twind.cjs",
  "exports": {
    ".": {
      "node": "./twind.cjs",
      "script": "./twind.umd.js",
      "module": "./twind.js",
      "types": "./twind.d.ts",
      "default": "./twind.js"
    }
  },
  "module": "./twind.js",
  "unpkg": "./twind.umd.js",
  "types": "./twind.d.ts"
}
```

**Comment by JoviDeCroock** [comment] 2020-12-30 10:55
I think that should work yes, `script` isn't considered by `wmr` so the only conflict was `node` vs `default`. I haven't tested it myself but from what @rschristian said it worked when `node` was removed.

**Comment by smeijer** [comment] 2020-12-30 13:28
> I know that @smeijer has been trying to use Twind with WMR, he might have some insight. 

I was experiencing troubles with this method as well. At the moment I'm using the hosted shim method, which works fine for development.

```
// add to <head>
<script type="module" src="https://cdn.skypack.dev/twind/shim"></script>
```

**Comment by sastan** [comment] 2020-12-30 13:47
I'll going to provide a PR using module and test it with wmr.

**Comment by sastan** [comment] 2020-12-30 14:42
I have published twind v0.10.3-0 (tag experimental) for testing. For me it is still not working. What am i missing?

```json
{
  "main": "./twind.cjs",
  "exports": {
    ".": {
      "node": "./twind.cjs",
      "module": "./twind.js",
      "script": "./twind.umd.js",
      "types": "./twind.d.ts",
      "default": "./twind.js"
    },
  "module": "./twind.js",
  "unpkg": "./twind.umd.js",
  "types": "./twind.d.ts"
}
```

**Comment by nmasella** [comment] 2020-12-30 15:19
Hi, thanks everyone for the support. I confirm that I have not been able to solve the problem but I continue to follow the discussion with interest.

Thanks again

**Comment by rschristian** [comment] 2020-12-30 17:47
@sastan `node` is always going to match first. It'll need to come after `module`

**Comment by sastan** [comment] 2020-12-30 18:00
Ah. That's my problem. I thought the order in keys (`['esmodules', 'import', 'module', 'require', 'browser', 'node', 'default']`) is determining what is used. Getting right on it.

**Comment by sastan** [comment] 2020-12-30 18:05
That was it!!!! I have a working wmr integration.

**Comment by sastan** [comment] 2020-12-30 18:07
Thanks everybody.

**Comment by nmasella** [comment] 2020-12-30 18:11
Wonderful @sastan , can i ask to share a complete example ?

**Closed** 2020-12-30 18:11 UTC

**Comment by sastan** [comment] 2020-12-30 18:13
Working on that already 😉  But i maybe finish that tomorrow. I'll create an release for you to use.

**Comment by nmasella** [comment] 2020-12-30 18:14
Thank you so much  :)

**Comment by sastan** [comment] 2020-12-30 18:17
Here you go: https://github.com/tw-in-js/twind/releases/tag/v0.10.3

**Comment by sastan** [comment] 2020-12-31 08:11
For all that are interested i have create an wmr example with prerendering: https://github.com/tw-in-js/example-wmr

I'll add that to the docs.

Please try it out.

**Comment by smeijer** [comment] 2020-12-31 08:37
That's awesome @sastan! Thanks for the example.

Related question, can a similar ssr experience be achieved when using the shim?

**Comment by sastan** [comment] 2020-12-31 08:52
I have created an issue (#45) to track the work that needs to be done to support ssr for twind/shim.
