### ISSUE TITLE
feature: Ability to add whitelist/safelist CSS classes

### ISSUE THREAD

**Issue by jsartisan** [tw-in-js/twind#218] opened 2021-10-18 12:14 UTC
sometimes users want to add some classes either to whitelist or safelist them. Similarly to what we have in tailwind here - https://tailwindcss.com/docs/upgrading-to-v2#update-purge-options-to-match-purge-css-3-0

A similar feature is required in twind too.

**Comment by bebraw** [comment] 2021-10-18 14:02
To give an idea of where this is needed, I have defined my components of my system in JSON. I push class names through `tw´ when possible but in cases like https://github.com/survivejs/gustwind/blob/main/components/tableOfContents.json, it's tough.

In the code I have set a HTML attribute like this `"x-class": "[state.textContent === parent.closest.textContent && 'underline', state.tagName === 'H3' && 'ml-2']"`. That means, it will generate some classes based on evaluation on client side. The problem is, the `underline` and `ml-2` classes won't get picked up as I don't push them through the `tw` utility.

Now that I think of it, I could probably solve it nicely on my side like this: `"x-class": "[state.textContent === parent.closest.textContent && tw('underline'), state.tagName === 'H3' && tw('ml-2')]"`. In other words, I can expose `tw` in my project to the value since it's evaluated anyway.

**Comment by bebraw** [comment] 2021-11-12 19:07
I think we have a way to do this already. I realized simply using the `tw` utility is enough.

I ended up doing something along `tw("hidden bg-gray-400 p-2");` to add the missing classes coming from dynamic code.

It might be more of a documentation issue then.

**Comment by sastan** [comment] 2022-01-25 19:00
In twind v1 we have a `ignorelist` option. All classes that match these are ignored and not handled by twind.

We did not add `safelist` because that could be done by calling `tw` like @bebraw suggested. 

Please give v1 a try. Here are some links to get you started:

- [The v1 branch](https://github.com/tw-in-js/twind/tree/next)
- [Reference](https://github.com/tw-in-js/twind/blob/next/documentation/40-reference/README.md) until the website is ready
- [Examples](https://github.com/tw-in-js/twind/tree/next/examples) — the [CDN example](https://github.com/tw-in-js/twind/tree/next/examples/twind-cdn) could be a good start

Closing this for now. Feel free to re-open.

**Closed by sastan** 2022-01-25 19:00 UTC

**Comment by grenierdev** [comment] 2022-09-15 01:09
@sastan I haven't found out how we can add classes to the `<body>` when doing [server side render](https://twind.dev/handbook/the-shim.html#server) without resorting to preflight.

Usually, with Tailwind, I'd just place my classes in the `safelist` and be done with it.

**Comment by grenierdev** [comment] 2022-10-04 23:17
@sastan Much appreciated!
