### ISSUE TITLE
Unify various modules and helpers

### ISSUE THREAD

**Issue by lukejacksonn** [tw-in-js/twind#157] opened 2021-03-24 15:27 UTC
## What

Twind started as a single module  that exported `setup` and `tw`. As the project has evolved we have added helpers like `css`/`apply`/`style` and other features to support things like the shim, SSR and CLI. Now we are coming up to V1 we are looking to clean up and consolidate the Twind offering somewhat.

The general idea here is to create an interface something like this for the client and server respectively:

```js
import { setup, tw, css, apply, style, sheets } from "twind";
import { setup, extract, sheets } from "twind/server";
```

## Why

The aim is to make things a little more intuitive, improve discoverability and make documentation easier. We have witnessed developers struggling to know what to import where and wondering whether they are doing it _right_. The proposal aims to create just one way to do things.

### Bundle Size

Unifying modules like this is likely to increase the overall bundle size by a couple of KB (from ~14 to 16). Time taken to download/parse Twind is always a primary concern but we think the pros outweigh the cons here. Another thing to note is that the module will be tree-shakeable so if you are using a bundler and don't use `css` for example, then it won't be bundled into your application.

### Shim by default

You might notice that the shim is not exposed by the proposed interface. The more we have used Twind ourselves or seen it been used by others, we have noticed that the shim is the easiest and most popular mechanism for both server and client. Going forward we would like to make this the default behaviour and have things _just work_. This means that the go to way of adding styles to your app will be via `class="bg-black text-white"` which comes with the advantage of aligning static HTML and virtual DOM implementations. We appreciate that not every application will require the _runtime_ component which activates the MutationObserver (and allows for the better dev tools experience) so we are proposing that this can be disabled by config similarly to the autoprefixer and hashing `setup({ runtime: false })`.

### Tailwind Utilities

By default Twind includes Tailwind theme/variants/utilities definitions because it is a comprehensive and well documented preset. However this is where the vast majority of Twind's filesize comes from. Something we have been considering lately is abstracting these out to `twind/tailwind` which make Twind core offering very obvious and promote the idea of developers/companies to create their own design system that they can use with Twind much like we do by default with Tailwind as a basis today. This _might_ also allow developers to create custom builds that only import the utilities they need resulting in smaller bundles for everyone.

The downside of this however is (quite contrary to the primary goal here) that it would requires something like this:

```js
import { setup, tw, css, apply, style, sheets } from "twind";
import * as tailwind from "twind/tailwind"

setup({ presets: [{ ...tailwind }] });
```

With that said, this is probably something we could either a) do internally but still apply Tailwind presets by default or b) not do at all c) embrace the ideal wholly knowing that extra import only has to be done once during setup.

## RFC

I'm creating this issue to gather feedback, thoughts and further considerations that we might not have been noted here. If you have and bright ideas or strong opinions on any aspect of this proposal then please comment below and I will update this description accordingly.

/cc @tw-in-js/contributors

**Comment by danielweck** [comment] 2021-03-26 15:34
> Unifying modules like this is likely to increase the overall bundle size by a couple of KB (from ~14 to 16).

Unless I am mistaken, I think that the advertized 14-16KB footprint is slightly misleading. There are several other CSS-in-JS libs that claim "near-zero" / "tiny" runtime, sometimes optimistically. In contrast, Twind offers complete Tailwind CSS support (and more) for a relatively small price, which I believe is worth documenting more openly.

Let's break it down:

I believe the currently-advertized bundle size corresponds to the "minimal" Twind runtime which excludes the `style-vendorizer` import (external), and also excludes the separate package entries: `twind/colors`, `twind/css`, `twind/observe`, `twind/server`, `twind/sheets`, `twind/shim`, `twind/shim/server`, `twind/style`. The quoted size represents the single file / minified ES Module (i.e. multiple exports for the entire "minimal"  Twind API), with HTTP gzip compression (not Brotli?).

https://bundlephobia.com/result?p=twind@0.16.9

https://unpkg.com/browse/twind@0.16.9/

Now, in my pet project (i.e. a small performance-oriented Preact WMR website), the Rollup-bundled and Terser-minified JS chunk dedicated to Twind weighs in at 35KB without any plugins. The actual practical size is 53KB with the "typography" and "forms" plugins (and I plan to use other ones too). These KB figures are on-disk sizes, before gzip compression. Note that I use `twind/style` and `twind/css` (2KB each), and at some point I will probably use `twind/colors` too (+ 3KB). PS: I have a separate chunk for static SSR, which bundles `twind/server` and `twind/sheets` (transitively).

The 50+KB (pre-compression) Twind-dedicated JS bundle is actually never loaded in the frontend of my production builds, but I suspect that I am the exception to the rule: the vast majority of Twind users / developers will ship the runtime, which is; all things considered; relatively lightweight given Twind's rich feature set. I just don't think 16KB is achievable in real-word use.

**Comment by danielweck** [comment] 2021-03-26 15:36
> we are proposing that this can be disabled by config similarly to the autoprefixer and hashing `setup({ runtime: false })`.

Yes please 👍  :)

**Comment by danielweck** [comment] 2021-03-26 15:56
> Tailwind Utilities:
> ```js
> setup({ presets: [{ ...tailwind }] });
> ```

That would be great!

I only had a superficial look at the core lib's source code, so I don't have a clear picture of how costly it would be to factor out the Tailwind definitions (in terms of development effort). But if you guys feel you can do it, I will totally root for you ;)

I wonder if Twind plugins could be harmonized based on the same architectural principles (i.e. declarative CSS definitions + small integration API), and whether or not this could help power the typescript language service (see https://github.com/tw-in-js/typescript-plugin/issues/8 )

It would be nice if there was a default `setup()` which imported all TW definitions (just like now), and a separate `setupMini()` for advanced usage (e.g. import partial TW definitions from Twind's preset, or an entirely different preset altogether, or mixed / merged).

Regarding tree shaking / dead code detection: I don't have a clear idea of how granular the TW definitions are / can be in Twind's code, but once factored out it should be possible to identify atoms of functionality that can safely be excluded from production JS bundles.

Seems like a ton of work, but if you guys can do it :) 👍

**Comment by sastan** [comment] 2021-03-26 15:58
@danielweck We are talking about compressed file sizes here. In one of the latest commits I've updated size-limit to show some more stats (the sub-modules do not include twind as dependency):

![Bildschirmfoto 2021-03-26 um 16 49 12](https://user-images.githubusercontent.com/514405/112657945-335b8e00-8e53-11eb-9778-d28de5862d05.png)

I believe that these are the stats we should talk about: 

- size with all dependencies, minified and brotli
- total time (loading time on slow 3G + running time  on Snapdragon 410)

How much raw JS there is not important most of the time. What matters are how much must be parsed and how much is evaluated when importing the module.

These things are reflected in the running time. I know that this is not what people are used to but that is what matters.

That is why we should talk/mention total time (load  +eval) and size (minified & brotli).

**Comment by danielweck** [comment] 2021-03-26 16:13
> We are talking about compressed file sizes here.

Of course. I thought this was clear in my comment, sorry if it wasn't.

Looking at Bundlephobia numbers, and then looking at Twind's bundle ESM code in the "core lib", `style-vendorizer` is external. More importantly, real world applications are very likely to use the other `twind/xxx` packages, along with common plugins. So my point still stands that the advertised KB need to be put into a very specific context.

I love your updated Brotli figures by the way! :) As expected, better than gzip. Can you please verify that `style-vendorizer` is indeed included in the tested bundles?

https://bundlephobia.com/result?p=style-vendorizer@2.0.0

**Comment by danielweck** [comment] 2021-03-26 16:22
> I believe that these are the stats we should talk about:
> 
>     * size with all dependencies, minified and brotli
> 
>     * total time (loading time on slow 3G + running time  on Snapdragon 410)
> 
> How much raw JS there is not important most of the time. What matters are how much must be parsed and how much is evaluated when importing the module.
> 
> These things are reflected in the running time. I know that this is not what people are used to but that is what matters.
> 
> That is why we should talk/mention total time (load +eval) and size (minified & brotli).

I couldn't agree more. Lighthouse screenshots with vanilla HTML+Twind integration would illustrate this quite well (I mean: no (P)React, Vue, Solid, etc.)

Naturally, in a web app with a giant DOM, lots of inline SVG, non-lazy image loading, non-deferred scripts, analytics, ads, etc., the impact of Twind runtime will be relatively minimal :)

**Comment by danielweck** [comment] 2021-03-26 17:14
**Fun test**: use Twind/shim to render https://tailwindcss.com (a really impressive landing page packed with cool interactives!)

____

I "downloaded" a local copy of the website's landing page ("save as" from Chrome), and I ran Lighthouse's "performance" test from a localhost HTTP server:

# Desktop:

<img width="734" alt="Screenshot 2021-03-26 at 16 43 19" src="https://user-images.githubusercontent.com/625201/112665517-0e671b00-8e53-11eb-978b-3d290237b457.png">

<img width="734" alt="Screenshot 2021-03-26 at 16 53 30" src="https://user-images.githubusercontent.com/625201/112666397-0cea2280-8e54-11eb-87a5-d065aadaf422.png">

# Mobile: 

<img width="734" alt="Screenshot 2021-03-26 at 16 44 14" src="https://user-images.githubusercontent.com/625201/112665621-2b9be980-8e53-11eb-9831-77bbd961434d.png">

<img width="734" alt="Screenshot 2021-03-26 at 16 53 53" src="https://user-images.githubusercontent.com/625201/112666423-13789a00-8e54-11eb-8839-4034bef9e6d7.png">

____

Then, I removed the Tailwind CSS stylesheet, and I added:

`<script type="module" src="https://cdn.skypack.dev/twind/shim"></script>`

(Skypack CDN, but I ran a local test too, see further below)

# Desktop:

<img width="734" alt="Screenshot 2021-03-26 at 16 42 49" src="https://user-images.githubusercontent.com/625201/112665761-4f5f2f80-8e53-11eb-87cd-c1e32bc10b53.png">

<img width="734" alt="Screenshot 2021-03-26 at 16 58 40" src="https://user-images.githubusercontent.com/625201/112666975-a3b6df00-8e54-11eb-8606-2feae6d5b9cb.png">

# Mobile:

<img width="734" alt="Screenshot 2021-03-26 at 16 41 39" src="https://user-images.githubusercontent.com/625201/112665803-59812e00-8e53-11eb-85c3-b63cc564c2fd.png">

<img width="734" alt="Screenshot 2021-03-26 at 16 59 11" src="https://user-images.githubusercontent.com/625201/112667011-ad404700-8e54-11eb-857d-2cf2723658d1.png">

____

Finally, I replaced the Skypack CDN Twind/shim script link with locally-hosted copies:

# Desktop

<img width="734" alt="Screenshot 2021-03-26 at 17 09 16" src="https://user-images.githubusercontent.com/625201/112668391-5cc9e900-8e56-11eb-85b4-ee87589aea7d.png">

<img width="734" alt="Screenshot 2021-03-26 at 17 09 43" src="https://user-images.githubusercontent.com/625201/112668415-65222400-8e56-11eb-9db7-e52d6ea89dba.png">

# Mobile

<img width="734" alt="Screenshot 2021-03-26 at 17 10 20" src="https://user-images.githubusercontent.com/625201/112668441-6d7a5f00-8e56-11eb-9860-3cbf4ed334ca.png">

<img width="734" alt="Screenshot 2021-03-26 at 17 10 49" src="https://user-images.githubusercontent.com/625201/112668463-73704000-8e56-11eb-94b3-8f8519b61a4b.png">

**Comment by danielweck** [comment] 2021-03-26 17:21
Here's the performance flamegraph:

# Without Twind:

<img width="1009" alt="Screenshot 2021-03-26 at 17 18 46" src="https://user-images.githubusercontent.com/625201/112669283-6ef85700-8e57-11eb-9864-49639a00c308.png">

# With Twind:

(the activity graph on the left hand side is Twind's `observe` aka "shim" immediately after `DOMContentLoaded`, working its way through the DOM to build the stylesheet just-in-time)

<img width="1009" alt="Screenshot 2021-03-26 at 17 18 03" src="https://user-images.githubusercontent.com/625201/112669311-79b2ec00-8e57-11eb-87d5-8bf42df3ec39.png">

**Comment by sastan** [comment] 2021-03-26 17:23
These results are to be expected because the shim kicks in **after** [DOMContentLoaded](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event).

For production sites we recommend critical CSS extraction.

I'm currently experimenting with one or two ways to optimize this. One of them is:

```js
<script>
// Inline https://unpkg.com/twind/twind.umd.js
// Inline https://unpkg.com/twind/observe/observe.umd.js

twindObserve.observe(document.documentElement)
</script>
```

Could you try that one?

**Comment by danielweck** [comment] 2021-03-26 17:25
> Could you try that one?

Sure. My current test is with:

```html
  <!-- script type="module" src="https://cdn.skypack.dev/twind/shim"></script -->
<!-- LOCALHOST COPY: -->
  <script type="module" src="./shim.js"></script>
```

**Comment by sastan** [comment] 2021-03-26 17:28
This is quite intersting.  Could we move that into discussion or discord.

**Comment by danielweck** [comment] 2021-03-26 17:29
Much better :)

# Desktop

<img width="1009" alt="Screenshot 2021-03-26 at 17 27 51" src="https://user-images.githubusercontent.com/625201/112670351-b7fcdb00-8e58-11eb-82ff-546820807842.png">

<img width="1009" alt="Screenshot 2021-03-26 at 17 28 12" src="https://user-images.githubusercontent.com/625201/112670368-bcc18f00-8e58-11eb-8e9f-f55864593246.png">

**Comment by danielweck** [comment] 2021-03-26 17:29
> @danielweck This is quite intersting. Could we move that into discussion or discord.

I will do.

**Comment by danielweck** [comment] 2021-03-26 17:30
# Mobile

<img width="1009" alt="Screenshot 2021-03-26 at 17 30 03" src="https://user-images.githubusercontent.com/625201/112670567-fbefe000-8e58-11eb-8bff-535499a6f6b7.png">

<img width="1009" alt="Screenshot 2021-03-26 at 17 30 26" src="https://user-images.githubusercontent.com/625201/112670583-00b49400-8e59-11eb-9254-f9e944221540.png">

**Comment by danielweck** [comment] 2021-03-26 17:39
I created a separate GitHub "discussion": https://github.com/tw-in-js/twind/discussions/161

**Comment by lukejacksonn** [comment] 2021-03-30 09:35
Thanks for your comments @danielweck I will follow the conversation on the thread you created (as this was not really the intended topic here) but just to let you know that I'm working on a "not so pet project" (a global ecommerce site) and we only have ~16KB of compressed twind imported at runtime (which includes tw/shim/css/style). All critical CSS is statically extracted during SSR with twind/next.

So in that sense I think that is is reasonably reasonable to state this kind of JS size, excluding of course all the additional "non-essential" modules like typography and forms.

**Comment by danielweck** [comment] 2021-03-30 10:04
Thanks Luke, good to hear about Twind being used in production websites.
In my small-scale tests the main impact of Twind runtime is not so much its total bundle size, but the impact on web vitals on mobile devices from Twind shim/observe, during stylesheet hydration (i.e. reconciliation / merging of SSR prerendered CSS with dynamically-generated class selectors + rules).

I don't use Next.js, and my use case is certainly different. I use Preact WMR (crucially: static SSR, not dynamic route prerendering), so I generate an inline critical / minimal CSS style element for pre-hydration initial render, as well as a separate async external stylesheet for other styles used post-hydration. This way, I am able to completely negate the need for the Twind runtime / just-in-time resolver.

The Twind CLI which extracts styles ahead of time is very useful in many cases, but there are significant caveats (by design, not bugs) which stop me from using this utility. Plus, the WMR pre/post processing plugin pipeline and Preact's VNode interceptor allow me to more accurately extract used Twind CSS.

If you don't mind me asking, do you use Twind's open source Next.js integration, or some in-house solution?

Cheers, Daniel

**Comment by lukejacksonn** [comment] 2021-04-07 12:45
Only just seen this reply so thanks for your patience. We are using `@twind/next` out of the box with no special configuration. It works absolutely great. The critical CSS is extracted to a style tag at the top of the page on first load SSR.. after that the shim kicks in and handles dynamic styles at runtime (think a modal that was opened by the user after page load that requires styling). This comes with the added benefit of not shipping potentially unused styles to the client, but obviously this is a tradeoff.

I'm still unsure of how valid the concern is of performance degradation when it comes to loading in Twind. On our netlify deploy environments we were seeing lighthouse perf scores ~90 and once we promoted the site to a production like environment we are seeing that go up to ~100 for desktop at least.

I do agree however that it would be interesting to see how we could make hydration more efficient. My initial approach would be to send down a map of already computed rules (essentially a serialized version of the cache that Twind would generate on the server) to prevent duplication of work by the browser. It sounds easy enough but I'm sure it comes with drawbacks/complications that I have not considered.

**Comment by bebraw** [comment] 2021-10-12 09:50
I've been using Twind in a Deno environment. There's one problem related to this issue in that case which you might want to consider.

At https://unpkg.com/twind@0.16.16/twind.js, there's a dependency on **style-vendorizer** (i.e. `import {cssPropertyAlias, cssPropertyPrefixFlags, cssValuePrefixFlags} from "style-vendorizer";`) and that won't work out of box with Deno. To solve, I've defined an alias against it using import maps (`"style-vendorizer": "https://unpkg.com/style-vendorizer@2.1.1/dist/esm/bundle.min.mjs",`).

Although this works, it fails when you want to use Twind within a web worker as import maps aren't supported there yet (https://github.com/denoland/deno/issues/6675).

If you re-architect this portion of Twind, maybe a good option here would be to allow the consumers to inject **style-vendorizer** somehow or at least have it as an optional dependency for the project.

**Comment by sastan** [comment] 2022-01-25 19:03
Implemented in twind v1.

Please give it a try. Here are some links to get you started:

- [The v1 branch](https://github.com/tw-in-js/twind/tree/next)
- [Reference](https://github.com/tw-in-js/twind/blob/next/documentation/40-reference/README.md) until the website is ready
- [Examples](https://github.com/tw-in-js/twind/tree/next/examples) — the [CDN example](https://github.com/tw-in-js/twind/tree/next/examples/twind-cdn) could be a good start

Closing this for now. Feel free to re-open.

**Closed by sastan** 2022-01-25 19:03 UTC
Labels: 💡 Proposal
