### ISSUE TITLE
Overlapping classes

### ISSUE THREAD

**Issue by mfolnovic** [tw-in-js/twind#14] opened 2020-12-24 06:47 UTC
Hello!

Awesome work on this library, feels amazing! 🎉 

In React, we have a scenario which we have troubles solving using tailwindcss, but feels like we should be able to solve it using something like this. Imagine a React component that has some tailwindcss classes defined in implementation, but also receives a className prop that should be able to override it.

An example:

```
function Button({ className = "", children }) {
  return (
    <button className={tw("border text-white bg-blue-600", className)}>{children}</button>
  );
}
```

If I use this component as: `<Button>blue</Button>`, button should be blue, but if I try to pass `bg-red-600` as `className`, `<Button className="bg-red-600">red</Button>`, then it should be red. Because of the way classes are applied (based on order in stylesheet), this isn't possible without removing `bg-blue-600` from className.

I wrote simple demo available [here](https://esm.codes/#aW1wb3J0IHsgdHcgfSBmcm9tICdodHRwczovL2Nkbi5za3lwYWNrLmRldi90d2luZCcKCmNvbnN0IHRvcENsYXNzTmFtZSA9IHR3KHsKICAiaC00MCBib3JkZXItMiBib3JkZXItcmVkLTEwMCBiZy1wdXJwbGUtNDAwIjogdHJ1ZSwKICAiYmctcmVkLTQwMCI6IHRydWUsCn0pOwoKY29uc3QgYm90dG9tQ2xhc3NOYW1lID0gdHcoewogICJiZy1yZWQtNDAwIjogdHJ1ZSwKICAiaC00MCBib3JkZXItMiBib3JkZXItcmVkLTEwMCBiZy1wdXJwbGUtNDAwIjogdHJ1ZSwKfSk7Cgpkb2N1bWVudC5ib2R5LmlubmVySFRNTCA9IGAKICA8ZGl2IGNsYXNzPSIke3RvcENsYXNzTmFtZX0iPgogICAgc2hvdWxkIGJlIHJlZAogIDwvZGl2PgogIDxkaXYgY2xhc3M9IiR7Ym90dG9tQ2xhc3NOYW1lfSI+CiAgICBzaG91bGQgYmUgcHVycGxlCiAgPC9kaXY+CmA=) using twind that demonstrates simple scenario that doesn't work.

Is there a theoretical way to make this work with this approach? I'd be willing to contribute with a bit of guidance. :)

**Comment by sastan** [comment] 2020-12-24 07:19
There are several ways to solve this:

1. use `!` as modifier ([docs](https://github.com/tw-in-js/twind/blob/main/docs/tailwind-extensions.md)) 

```jsx
<Button className="bg-red-600!">red</Button>
```

[Example](aW1wb3J0IHsgdHcgfSBmcm9tICdodHRwczovL2Nkbi5za3lwYWNrLmRldi90d2luZCcKCmNvbnN0IHRvcENsYXNzTmFtZSA9IHR3KHsKICAiaC00MCBib3JkZXItMiBib3JkZXItcmVkLTEwMCBiZy1wdXJwbGUtNDAwIjogdHJ1ZSwKICAiYmctcmVkLTQwMCI6IHRydWUsCn0pOwoKY29uc3QgYm90dG9tQ2xhc3NOYW1lID0gdHcoewogICJiZy1yZWQtNDAwIjogdHJ1ZSwKICAiaC00MCBib3JkZXItMiBib3JkZXItcmVkLTEwMCBiZy1wdXJwbGUtNDAwISI6IHRydWUsCn0pOwoKZG9jdW1lbnQuYm9keS5pbm5lckhUTUwgPSBgCiAgPGRpdiBjbGFzcz0iJHt0b3BDbGFzc05hbWV9Ij4KICAgIHNob3VsZCBiZSByZWQKICA8L2Rpdj4KICA8ZGl2IGNsYXNzPSIke2JvdHRvbUNsYXNzTmFtZX0iPgogICAgc2hvdWxkIGJlIHB1cnBsZQogIDwvZGl2Pgpg)

2. Use a dedicated property

```jsx
function Button({ bgColor = "blue-600", className, children }) {
  return (
    <button className={tw`border text-white bg-${bgColor} ${className}`}>{children}</button>
  );
}

<Button bgColor="red-600">red</Button>
```


_One remark on performance_: Try to use the template literal syntax as it allows to cache the static parts (`tw` will ignore falsey values):

```jsx
function Button({ className = "", children }) {
  return (
    <button className={tw`border text-white bg-blue-600 ${className}`}>{children}</button>
  );
}
```

**Comment by sastan** [comment] 2020-12-24 07:39
We are planing to add a best practices guide. These kind of questions are very important to use. Thank you.

Your [demo](https://esm.codes/#aW1wb3J0IHsgdHcgfSBmcm9tICdodHRwczovL2Nkbi5za3lwYWNrLmRldi90d2luZCcKCmNvbnN0IHRvcENsYXNzTmFtZSA9IHR3KHsKICAiaC00MCBib3JkZXItMiBib3JkZXItcmVkLTEwMCBiZy1wdXJwbGUtNDAwIjogdHJ1ZSwKICAiYmctcmVkLTQwMCI6IHRydWUsCn0pOwoKY29uc3QgYm90dG9tQ2xhc3NOYW1lID0gdHcoewogICJiZy1yZWQtNDAwIjogdHJ1ZSwKICAiaC00MCBib3JkZXItMiBib3JkZXItcmVkLTEwMCBiZy1wdXJwbGUtNDAwIjogdHJ1ZSwKfSk7Cgpkb2N1bWVudC5ib2R5LmlubmVySFRNTCA9IGAKICA8ZGl2IGNsYXNzPSIke3RvcENsYXNzTmFtZX0iPgogICAgc2hvdWxkIGJlIHJlZAogIDwvZGl2PgogIDxkaXYgY2xhc3M9IiR7Ym90dG9tQ2xhc3NOYW1lfSI+CiAgICBzaG91bGQgYmUgcHVycGxlCiAgPC9kaXY+CmA=) could be written like this for optimal performance (only meant for future reference):

- using inline plugins: [Demo](https://esm.codes/#aW1wb3J0IHsgdHcgfSBmcm9tICdodHRwczovL2Nkbi5za3lwYWNrLmRldi90d2luZCcKCmNvbnN0IHNoYXJlZCA9ICh7IHR3IH0pID0+IHR3YGgtNDAgYm9yZGVyKDIgcmVkLTEwMClgCi8vIGNvbnN0IHNoYXJlZCA9IHR3YGgtNDAgYm9yZGVyKDIgcmVkLTEwMClgCgpjb25zdCB0b3BDbGFzc05hbWUgPSB0d2Ake3NoYXJlZH0gYmctcmVkLTQwMGAKY29uc3QgYm90dG9tQ2xhc3NOYW1lID0gdHdgJHtzaGFyZWR9IGJnLXB1cnBsZS00MDBgCgpkb2N1bWVudC5ib2R5LmlubmVySFRNTCA9IGAKICA8ZGl2IGNsYXNzPSIke3RvcENsYXNzTmFtZX0iPgogICAgc2hvdWxkIGJlIHJlZAogIDwvZGl2PgogIDxkaXYgY2xhc3M9IiR7Ym90dG9tQ2xhc3NOYW1lfSI+CiAgICBzaG91bGQgYmUgcHVycGxlCiAgPC9kaXY+CmA=)

```js
import { tw } from 'https://cdn.skypack.dev/twind'

const shared = ({ tw }) => tw`h-40 border(2 red-100)`
// const shared = tw`h-40 border(2 red-100)`

const topClassName = tw`${shared} bg-red-400`
const bottomClassName = tw`${shared} bg-purple-400`

document.body.innerHTML = `
  <div class="${topClassName}">
    should be red
  </div>
  <div class="${bottomClassName}">
    should be purple
  </div>
`
```

- using base style with `!` overrides: [Demo](https://esm.codes/#aW1wb3J0IHsgdHcgfSBmcm9tICdodHRwczovL2Nkbi5za3lwYWNrLmRldi90d2luZCcKCmNvbnN0IGJhc2VDbGFzc05hbWUgPSB0d2BoLTQwIGJvcmRlcigyIHJlZC0xMDApIGJnLXJlZC00MDBgCmNvbnN0IGJvdHRvbUNsYXNzTmFtZSA9IHR3YCR7YmFzZUNsYXNzTmFtZX0gYmctcHVycGxlLTQwMCFgCgpkb2N1bWVudC5ib2R5LmlubmVySFRNTCA9IGAKICA8ZGl2IGNsYXNzPSIke2Jhc2VDbGFzc05hbWV9Ij4KICAgIHNob3VsZCBiZSByZWQKICA8L2Rpdj4KICA8ZGl2IGNsYXNzPSIke2JvdHRvbUNsYXNzTmFtZX0iPgogICAgc2hvdWxkIGJlIHB1cnBsZQogIDwvZGl2PgpgCg==)

´´´js
import { tw } from 'https://cdn.skypack.dev/twind'

const baseClassName = tw`h-40 border(2 red-100) bg-red-400`
const bottomClassName = tw`${baseClassName} bg-purple-400!`

document.body.innerHTML = `
  <div class="${baseClassName}">
    should be red
  </div>
  <div class="${bottomClassName}">
    should be purple
  </div>
`
```

Please let us know what to think, if you have any more questions or improvements (API, docs) you like to see.

**Comment by gojutin** [comment] 2020-12-26 18:46
Hi all, 

twind authors- Brilliant work! 👏

As for overlapping classes..this is a problem I also often encounter when creating sharable React components using Tailwind. I think it's a very common scenario to want to provide default classes that are easily overridable at an instance level. It seems like the Tailwind docs encourage component abstractions, but at the same time, you can’t pass `text-blue-500` to a component that has a competing text color class already defined (as an example). You would expect the last-defined className to win, but this is not usually the case. 

For myself, custom props to define styles are not an ideal solution. I think `!` is an okay solution from the user’s perspective, but it requires the use of `important!`, which is probably best reserved for more dire situations.

I would love to see the compiler handle smart merging of competing classes as a first-class feature. I realize that this is not easy and there are lots of considerations like how to handle variants and similiar directives. But, it would be really nice not to have to think about it!

A (possibly bad) idea that came to mind:

A custom `default` variant. 

- More declarative
- Possibly easier to parse?

```tsx
// Reusable Button Component 
const Button = ({children, className, ...rest}) => {
  const mergedClassNames = tw`default:text-blue-500 text-xl ${props.className}`;
  // or tw`text(default:blue-500 xl) ${props.className}`;

  return (
    <button className={mergedClassNames} {...rest}>
      {children}
    </button>
  )
}

// Using the Button 
const App = () => (
  <Button className={tw`text-purple-500`}>Purple Wins</Button>
)
```

**Comment by sastan** [comment] 2020-12-27 10:58
Thanks for the detailed description.

I don't know if we can ever support `default` or resolving of overlapping classes. The problem is that `text-*`  is not only for `color` but used for a _lot_ of different styles. This would mean that the parser or translator needs to have deep knowledge about what CSS styles a plugin generates for a directive and de-duplicates those based on the CSS properties in the resulting CSS object.

Additionally this would introduce another presedence dimension: the order directives are written.

We have two user-land solutions for this kind of problem:

1. Use `!` as modifier
2. Use a dedicated property `color` property

I can understand why you would like an integrated solution for this.

Please investigate further and keep use informed about your findings.

**Comment by gojutin** [comment] 2020-12-27 13:39
Thanks for the response. I’ve tried to implement something similar in the past so I definitely understand the challenges. My thought was that the use of the `default` variant could help in narrowing down the type of competing class names (`text-blue-500` vs `text-xl` for example). But, even then, you would need to generate all the available options on the fly or keep a list in memory. 

Either way, I appreciate the consideration and all the work you’ve put into this awesome project!

**Comment by sastan** [comment] 2020-12-27 17:42
I'm closing this for now. But feel free to re-open if needed...

**Comment by sastan** [comment] 2020-12-28 09:53
After a good night sleep i had an idea: an `overrides` variant (name to be discussed) - this variant would increase the selector specificity on rules it is applied to.



```js
tw`text-blue-500`
// => .text-blue-500 { ... }

tw`overrides:text-purple-500`
// => .text-purple-500.text-purple-500 { ... }
```

This could be use like this:

```js
const Button = ({ children, className, ...props }) => {
  const mergedClassNames = tw`text-blue-500 text-xl overrides:(${props.className})`
  return (
    <button className={mergedClassNames} {...props}>
      {children}
    </button>
  )
}

const App = () => (
  <Button className="text-purple-500 text-md">Purple and md Win</Button>
)
```

@mfolnovic @gojutin  Would that help?

**Comment by sastan** [comment] 2020-12-28 11:19
This can already be implements in user-land:

[Demo](https://esm.codes/#aW1wb3J0IHsgaCwgcmVuZGVyIH0gZnJvbSAnaHR0cHM6Ly9jZG4uc2t5cGFjay5kZXYvcHJlYWN0JwppbXBvcnQgaHRtIGZyb20gJ2h0dHBzOi8vY2RuLnNreXBhY2suZGV2L2h0bScKCmltcG9ydCB7IHR3LCBzZXR1cCB9IGZyb20gJ2h0dHBzOi8vY2RuLnNreXBhY2suZGV2L3R3aW5kJwoKY29uc3QgaHRtbCA9IGh0bS5iaW5kKGgpCgpzZXR1cCh7CiAgdmFyaWFudHM6IHsKICAgICc6b3ZlcnJpZGUnOiAnJiYnLAogIH0sCn0pCgoKY29uc3QgUCA9ICh7IGNoaWxkcmVuLCBjbGFzc05hbWUsIC4uLnByb3BzIH0pID0+IHsKICBjb25zdCBtZXJnZWRDbGFzc05hbWVzID0gdHdgdGV4dChibHVlLTUwMCAzeGwpIG92ZXJyaWRlOigke2NsYXNzTmFtZX0pYAogIHJldHVybiBodG1sYAogICAgPHAgY2xhc3NOYW1lPSR7bWVyZ2VkQ2xhc3NOYW1lc30gLi4uJHtwcm9wc30+CiAgICAgICR7Y2hpbGRyZW59CiAgICA8L3A+CiAgYAp9CgpyZW5kZXIoCiAgaHRtbGAKICAgIDxtYWluIGNsYXNzTmFtZT0iJHt0d2BoLXNjcmVlbiBmbGV4IGZsZXgtY29sIGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWNlbnRlciBjaGlsZHJlbjpteS00YH0iPgogICAgICA8JHtQfT4KICAgICAgICBEZWZhdWx0cwogICAgICA8Ly8+CiAgICAgIDwke1B9IGNsYXNzTmFtZT0idGV4dCg1eGwgcGluay03MDApIj4KICAgICAgICB3aXRoIG92ZXJyaWRlcwogICAgICA8Ly8+CiAgICA8L21haW4+CiAgYCwKICBkb2N1bWVudC5ib2R5LAopCg==)

```js
setup({
  variants: {
    ':override': '&&',
  },
})

const Button = ({ children, className, ...props }) => {
  const mergedClassNames = tw`text-blue-500 text-xl override:(${props.className})`
  return (
    <button className={mergedClassNames} {...props}>
      {children}
    </button>
  )
}

const App = () => (
  <Button className="text-purple-500 text-md">Purple and md Win</Button>
)
```

**Comment by gojutin** [comment] 2020-12-28 14:02
It's declarative, clearly defined in the rendered markup, and it works exactly as it should as far as I can tell. I think this is great!

**Comment by lukejacksonn** [comment] 2020-12-28 15:58
I concur. Simple, elegant solution that requires no changes to core, love it!

**Comment by sastan** [comment] 2020-12-28 16:34
@lukejacksonn I just have updated the styled PR and found that this `override` variant might be useful there as well. We should think about adding this to the core.

**Comment by lukejacksonn** [comment] 2020-12-28 16:45
Nice, I'm not against that at all!

**Closed** 2020-12-28 21:25 UTC
Labels: question
